### PR TITLE
Improve workflow for print/vet status tracking + public view page

### PR DESCRIPTION
**Pull request by sijie123**
- Add usercontest statuses: "print_ready" and "vetted"
- Modify translation workflow to include printing + vetting for onsite-teams
- Add public view page for all team translation status (optimized for broadcasting on zoom/projector)

### CODE REVIEW

**Comment by sijie123** [comment]
## Staff overall view
image
Overall view of all teams

image
Staff can update the print status once print-outs are ready and put into envelopes (ready for TL to vet)

image
After Team Leader vets the print-outs, staff can click the button to finalize

## Corresponding TL views

image
Translation frozen, pending print

image
Print Ready

image
Finalized / vetted

## Public broadcast / announcement view
image

**Comment by sijie123** [comment]
No permissions to request for view... @fushar @Si-plus-plus please help to review
Requires DB migration to add 2 new boolean fields indicating print ready and vetted respectively.

**Review by Si-plus-plus — APPROVED** [review]

**Comment by sijie123** [comment]
As discussed with @fushar, we think the "print ready" status is not needed as this is an extra step that the runners need to do and could cause more confusion.

Updated, simplified workflow:
Team Leader translating / choose copies --> Pending TL vet/sign (print + HTC put into envelope + runner to TL for checking) --> Done

**Comment by sijie123** [comment]
Updated UI

### Staff Overall View
image
Overall view of all teams

image
Now there's only 1 button to press (for on-site teams): TL checked and sealed.

image
After button pressed

image
For remote teams, this button doesn't appear at all.

### Corresponding TL Views
image
on-site, not yet started translation

image
Waiting for HTC to print + put into envelope + send runner

image
Done

Public / Broadcast View
image

**Comment by sijie123** [comment]
Ready for review again from @fushar and @Si-plus-plus 
Please kindly squash and merge when ready, my individual commits aren't exactly very pretty 😓

**Review by Si-plus-plus — APPROVED** [review]
lgtm!

**Review by Si-plus-plus — APPROVED** [review]

**Review by fushar — APPROVED** [review]
Thanks @sijie123 !

Small changes:

- Rename "vet" everywhere into "seal" to simplify the terms
- Removed the autorefresh on team homepage

Other than that, it worked really great.

**Pull request merged**
